name: Build Android App
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v1

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Build App
      run: ./gradlew build
    
    - name: Save the Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: keyboard
        path: app/build/outputs/apk
